<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Sprint Challenge
## *Data Science Unit 4 Sprint 1*

After a week of Natural Language Processing, you've learned some cool new stuff: how to process text, how turn text into vectors, and how to model topics from documents. Apply your newly acquired skills to one of the most famous NLP datasets out there: [Yelp](https://www.yelp.com/dataset/challenge). As part of the job selection process, some of my friends have been asked to create analysis of this dataset, so I want to empower you to have a head start.  

The real dataset is massive (almost 8 gigs uncompressed). I've sampled the data for you to something more managable for the Sprint Challenge. You can analyze the full dataset as a stretch goal or after the sprint challenge. As you work on the challenge, I suggest adding notes about your findings and things you want to analyze in the future.

## Challenge Objectives
*Successfully complete these all these objectives to earn a 2. There are more details on each objective further down in the notebook.*
* <a href="#p1">Part 1</a>: Write a function to tokenize the yelp reviews
* <a href="#p2">Part 2</a>: Create a vector representation of those tokens
* <a href="#p3">Part 3</a>: Use your tokens in a classification model on yelp rating
* <a href="#p4">Part 4</a>: Estimate & Interpret a topic model of the Yelp reviews

In [1]:
import pandas as pd

yelp = pd.read_json('./data/review_sample.json', lines=True)

In [2]:
yelp.head()

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id  
0  n1LM36qNg4rqGXIcvVXv8w  
1  5CgjjDAic2-FAvCtiHpytA  
2  BdV-cf3LScmb8kZ7iiBcMA  
3  cZZnBqh4gAEy4CdNvJailQ  
4  n9QO4ClYAS7h9fpQwa5bhA

## Part 1: Tokenize Function
<a id="#p1"></a>

Complete the function `tokenize`. Your function should
- accept one document at a time
- return a list of tokens

You are free to use any method you have learned this week.

In [3]:
import spacy
import en_core_web_md
from spacy.tokenizer import Tokenizer
nlp = en_core_web_md.load()
tokenizer = Tokenizer(nlp.vocab)

In [4]:
def tokenize(doc):
    
    return [token.text for token in tokenizer(doc)]

In [5]:
tokenize(yelp.text[0])

['BEWARE!!!',
 'FAKE,',
 'FAKE,',
 'FAKE....We',
 'also',
 'own',
 'a',
 'small',
 'business',
 'in',
 'Los',
 'Alamitos,',
 'CA',
 'and',
 'received',
 'what',
 'looked',
 'like',
 'a',
 'legitimate',
 'bill',
 'for',
 '$70',
 'with',
 'an',
 'account',
 'number',
 'and',
 'all.',
 ' ',
 'I',
 'called',
 'the',
 'phone',
 'number',
 'listed',
 '(866)',
 '273-7934.',
 ' ',
 'The',
 'wait',
 'time',
 'on',
 'hold',
 'said',
 '20',
 'minutes',
 'and',
 'to',
 'leave',
 'a',
 'message.',
 ' ',
 'I',
 'could',
 'not',
 'get',
 'a',
 'live',
 'person',
 'on',
 'the',
 'phone',
 'no',
 'matter',
 'what',
 'number',
 'I',
 'selected.',
 ' ',
 'I',
 'left',
 'a',
 'very',
 'FIRM',
 'message',
 'that',
 'I',
 'would',
 'be',
 'contacting',
 'the',
 'BBB',
 'and',
 'my',
 'attorney',
 'regarding',
 'their',
 'company',
 'trying',
 'to',
 'scam',
 'businesses.',
 'This',
 'has',
 'to',
 'be',
 'illegal!!!!!']

## Part 2: Vector Representation
<a id="#p2"></a>
1. Create a vector representation of the reviews
2. Write a fake review and query for the 10 most similiar reviews, print the text of the reviews. Do you notice any patterns?
    - Given the size of the dataset, it will probably be best to use a `NearestNeighbors` model for this. 

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english", max_features=5000)

dtm = tfidf.fit_transform(yelp.text)

representation = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())
representation.head()

00  000  00pm   07   10  100  1000  101  10pm   11  ...  yuck  yuk  yum  \
0  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
1  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
2  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
3  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
4  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   

   yummy  yup  zero  zone  zoo  zucchini  était  
0    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
1    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
2    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
3    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
4    0.0  0.0   0.0   0.0  0.0       0.0    0.0  

[5 rows x 5000 columns]

In [7]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=10, algorithm='kd_tree')

nn.fit(dtm.todense())

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)

In [30]:
fake = ['The food here is great.']
new = tfidf.transform(fake)
nn.kneighbors(new.todense())

(array([[0.94614938, 0.96104879, 0.98847001, 1.        , 1.        ,
         1.02657962, 1.03722145, 1.04966035, 1.05689601, 1.07644082]]),
 array([[5617, 1522, 3477, 6204, 6311, 1192,  151, 7594, 8133, 4546]],
       dtype=int64))

## Part 3: Classification
<a id="#p3"></a>
Your goal in this section will be to predict `stars` from the review dataset. 

1. Create a piepline object with a sklearn `CountVectorizer` or `TfidfVector` and any sklearn classifier. Use that pipeline to estimate a model to predict `stars`. Use the Pipeline to predict a star rating for your fake review from Part 2. 
2. Tune the entire pipeline with a GridSearch

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
vect = TfidfVectorizer(stop_words='english')
rfc = RandomForestClassifier()
pipe = Pipeline([('vect', vect), ('rfc', rfc)])
# Fit pipeline
pipe.fit(yelp.text, yelp.stars)

Pipeline(memory=None,
         steps=[('vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_patte...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None

In [31]:
# I guess it worked.
pipe.predict(fake)

array([5], dtype=int64)

In [11]:
# Tuning
from sklearn.model_selection import GridSearchCV

parameters = {
    'vect__max_df': (0.5, 0.75, 1),
    'rfc__max_depth': (20, 10, 100)
}

grid_search = GridSearchCV(pipe,parameters, cv=5, n_jobs=-1, verbose=1)
grid_search.fit(yelp.text, yelp.stars)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:   52.9s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('vect',
                                        TfidfVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.float64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=True,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                                        no

## Part 4: Topic Modeling

Let's find out what those yelp reviews are saying! :D

1. Estimate a LDA topic model of the review text
    - Keep the `iterations` parameter at or below 5 to reduce run time
    - The `workers` parameter should match the number of physical cores on your machine.
2. Create 1-2 visualizations of the results
    - You can use the most important 3 words of a topic in relevant visualizations. Refer to yesterday's notebook to extract. 
3. In markdown, write 1-2 paragraphs of analysis on the results of your topic model

__*Note*__: You can pass the DataFrame column of text reviews to gensim. You do not have to use a generator.

In [34]:
from gensim.models import LdaMulticore
from gensim.corpora import Dictionary
from gensim import corpora
from gensim.models import CoherenceModel
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS

def tokenize2(text):
  return [token for token in simple_preprocess(text) if token not in STOPWORDS]

Learn the vocubalary of the yelp data:

In [35]:
id2word = corpora.Dictionary([tokenize2(row) for row in yelp.text])

Create a bag of words representation of the entire corpus

In [36]:
corpus = [id2word.doc2bow(tokenize2(text)) for text in yelp.text]

Your LDA model should be ready for estimation: 

In [37]:
lda = LdaMulticore(corpus=corpus,
                   id2word=id2word,
                   iterations=5,
                   workers=4,
                   num_topics = 10 # You can change this parameter
                  )

Create 1-2 visualizations of the results

In [38]:
# lda_multicore =  models.LdaModel.load('lda_multicore.model')
from pprint import pprint
pprint(lda.print_topics())
doc_lda = lda[corpus]

[(0,
  '0.010*"good" + 0.010*"food" + 0.009*"great" + 0.009*"place" + 0.008*"like" '
  '+ 0.006*"service" + 0.005*"best" + 0.004*"time" + 0.004*"restaurant" + '
  '0.004*"ve"'),
 (1,
  '0.011*"place" + 0.008*"food" + 0.008*"like" + 0.008*"great" + '
  '0.007*"service" + 0.006*"time" + 0.006*"good" + 0.005*"ve" + 0.004*"little" '
  '+ 0.004*"love"'),
 (2,
  '0.011*"food" + 0.010*"great" + 0.009*"good" + 0.008*"place" + '
  '0.008*"service" + 0.007*"like" + 0.005*"best" + 0.005*"ve" + 0.004*"came" + '
  '0.004*"time"'),
 (3,
  '0.013*"food" + 0.012*"good" + 0.010*"service" + 0.009*"place" + '
  '0.008*"great" + 0.007*"time" + 0.005*"got" + 0.005*"like" + 0.004*"best" + '
  '0.004*"ordered"'),
 (4,
  '0.012*"place" + 0.011*"service" + 0.010*"good" + 0.008*"great" + '
  '0.007*"food" + 0.007*"like" + 0.007*"time" + 0.005*"got" + 0.004*"order" + '
  '0.004*"love"'),
 (5,
  '0.013*"time" + 0.013*"food" + 0.010*"place" + 0.009*"good" + 0.008*"great" '
  '+ 0.006*"like" + 0.006*"service" + 0.0

In [41]:
# Compute Perplexity
print('\nPerplexity: ', lda.log_perplexity(corpus))  # a measure of how good the model is. lower the better.


Perplexity:  -9.117874601680986


I didn't really go through the entire data set in detail since it was relatively large even for a sample size. The reviews that I did saw had a majority of them praising the restaurant for their service or food. There were hardly any negative reviews in this data set. My LDA model even shows all the topics having practically no negative adjectives. It seems that the sample size data set given to us this time tended to have a lot of positive reviews.

## Stretch Goals

Complete one of more of these to push your score towards a three: 
* Create more visualizations of the LDA results and provide written analysis
* Incorporate RandomizedSearchCV into docoument classification pipeline
* Incorporate named entity recognition into your analysis
* Compare vectorization methods in the classification section
* Analyze more (or all) of the yelp dataset - this one is v. hard. 
* Use a generator object on the reviews file - this would help you with the analyzing the whole dataset.
* Incorporate any of the other yelp dataset entities in your analysis (business, users, etc.)